### ISSUE TITLE
Issues compiling a project that uses the latest version of Quarkus

### ISSUE THREAD

**Issue by ntrp** [quarkiverse/quarkus-opencv#48]
When setting the versions to:
- Quarkus - 2.4.2.Final
- quarkus-opencv - 1.0.4

I get:
`Build step io.quarkiverse.opencv.deployment.OpenCVProcessor#nativeJni threw an exception: java.lang.NoSuchFieldError: containerBuild`

Anything I'm doing wrong or the lib needs an update?

**Comment by ntrp** [comment]
I tested locally and it worked fine when upgrading the Quarkus dependency in the lib to the same version. Would it make sense shifting the extension versioning scheme to the same used by Quarkus?

**Comment by gsmet** [comment]
The issue was already fixed in `main` but I forgot to release after 2.4 was fully released. Release is ongoing, I'll close when it hits Central.

As for shifting to the same version scheme, it's not really appropriate as breakages shouldn't happen that often so we don't release for every Quarkus release.

**Comment by gsmet** [comment]
1.1.0 is available on Maven Central and is compatible with Quarkus 2.4+.
